### ISSUE TITLE
Script is not downloading presenter content

### ISSUE THREAD

**Issue by arielf-mn** [AndrewJNet/CopyMMSFiles#10]
Ran script and it doesn't seem to download the *.pptx, *.pdf, etc for each session... :(

![image](https://user-images.githubusercontent.com/53094675/236293115-64e16bac-bdd8-4abb-8684-60878e5d8991.png)

**Comment by AndrewJNet** [comment]
Fixed by #11

**Comment by arielf-mn** [comment]
I have verified that it's downloading content now. Thank you for the fix!
