### ISSUE TITLE
Does Not Run on PowerShell Core 6

### ISSUE THREAD

**Issue by franklesniak** [AndrewJNet/CopyMMSFiles#5]
Cause:
The $web object does not have a property "Forms". Need to investigate/troubleshoot further.

**Comment by AndrewJNet** [comment]
Found this issue in the Powershell repo:

[https://github.com/PowerShell/PowerShell/issues/2867](https://github.com/PowerShell/PowerShell/issues/2867)

**Comment by AndrewJNet** [comment]
@franklesniak should we target PS7 for this?

**Comment by AndrewJNet** [comment]
Solved by #12
