### ISSUE TITLE
Header in CopyMMS2019Files.ps1 is Incorrect

### ISSUE THREAD

**Issue by franklesniak** [AndrewJNet/CopyMMSFiles#7]
Trivial, but the header/comments at the top of the CopyMMS2019Files.ps1 file are incorrect (referencing 2018 Desert Edition instead of 2019).

**Comment by AndrewJNet** [comment]
Quick resolution 👍 thanks for the issues this morning @franklesniak !

**Comment by franklesniak** [comment]
Hah, no problem! Can you tell I'm finally getting around to downloading content?

By the way, not meaning to "toss issues over the fence", here. I sent a note to my team inviting folks to help resolve.

**Comment by AndrewJNet** [comment]
No this is great! Appreciate it!
